// <auto-generated />
using System;
using AvcolStaff.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AvcolStaff.Migrations
{
    [DbContext(typeof(AvcolStaffContext))]
    [Migration("20210509053352_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AvcolStaff.Models.DepartmentStaff", b =>
                {
                    b.Property<int>("DepartmentStaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentsID")
                        .HasColumnType("int");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.HasKey("DepartmentStaffID");

                    b.HasIndex("DepartmentsID");

                    b.HasIndex("StaffID");

                    b.ToTable("DepartmentStaff");
                });

            modelBuilder.Entity("AvcolStaff.Models.DepartmentSubjects", b =>
                {
                    b.Property<int>("DepartmentSubjectsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentsID")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectsID")
                        .HasColumnType("int");

                    b.HasKey("DepartmentSubjectsID");

                    b.HasIndex("DepartmentsID");

                    b.HasIndex("SubjectsID");

                    b.ToTable("DepartmentSubjects");
                });

            modelBuilder.Entity("AvcolStaff.Models.Departments", b =>
                {
                    b.Property<int>("DepartmentsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(35)")
                        .HasMaxLength(35);

                    b.Property<int?>("StaffID")
                        .HasColumnType("int");

                    b.HasKey("DepartmentsID");

                    b.HasIndex("StaffID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("AvcolStaff.Models.PersonalInformation", b =>
                {
                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CitizenStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EcRelaitonship")
                        .IsRequired()
                        .HasColumnType("nvarchar(56)")
                        .HasMaxLength(56);

                    b.Property<string>("EmailAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Ethnicity")
                        .IsRequired()
                        .HasColumnType("nvarchar(56)")
                        .HasMaxLength(56);

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.HasKey("StaffID");

                    b.ToTable("PersonalInformation");
                });

            modelBuilder.Entity("AvcolStaff.Models.Rating", b =>
                {
                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.Property<int>("ReviewStars")
                        .HasColumnType("int");

                    b.HasKey("StaffID");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("AvcolStaff.Models.Sessions", b =>
                {
                    b.Property<int>("SessionsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.Property<int>("SubjectsID")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SessionsID");

                    b.HasIndex("StaffID")
                        .IsUnique();

                    b.HasIndex("SubjectsID")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("AvcolStaff.Models.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(35)")
                        .HasMaxLength(35);

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(35)")
                        .HasMaxLength(35);

                    b.Property<string>("TeacherCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffID");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("AvcolStaff.Models.Subjects", b =>
                {
                    b.Property<int>("SubjectsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(5)")
                        .HasMaxLength(5);

                    b.HasKey("SubjectsID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("AvcolStaff.Models.DepartmentStaff", b =>
                {
                    b.HasOne("AvcolStaff.Models.Departments", "Departments")
                        .WithMany()
                        .HasForeignKey("DepartmentsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvcolStaff.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AvcolStaff.Models.DepartmentSubjects", b =>
                {
                    b.HasOne("AvcolStaff.Models.Departments", "Departments")
                        .WithMany()
                        .HasForeignKey("DepartmentsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvcolStaff.Models.Subjects", "Subjects")
                        .WithMany()
                        .HasForeignKey("SubjectsID");
                });

            modelBuilder.Entity("AvcolStaff.Models.Departments", b =>
                {
                    b.HasOne("AvcolStaff.Models.Staff", null)
                        .WithMany("Departments")
                        .HasForeignKey("StaffID");
                });

            modelBuilder.Entity("AvcolStaff.Models.PersonalInformation", b =>
                {
                    b.HasOne("AvcolStaff.Models.Staff", "Staff")
                        .WithOne("PersonalInformation")
                        .HasForeignKey("AvcolStaff.Models.PersonalInformation", "StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AvcolStaff.Models.Rating", b =>
                {
                    b.HasOne("AvcolStaff.Models.Staff", "Staff")
                        .WithOne("Rating")
                        .HasForeignKey("AvcolStaff.Models.Rating", "StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AvcolStaff.Models.Sessions", b =>
                {
                    b.HasOne("AvcolStaff.Models.Staff", "Staff")
                        .WithOne("Sessions")
                        .HasForeignKey("AvcolStaff.Models.Sessions", "StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvcolStaff.Models.Subjects", "Subjects")
                        .WithOne("Sessions")
                        .HasForeignKey("AvcolStaff.Models.Sessions", "SubjectsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
