// <auto-generated />
using System;
using AvcolStaff.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AvcolStaff.Migrations
{
    [DbContext(typeof(AvcolStaffContext))]
    partial class AvcolStaffContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AvcolStaff.Models.Departments", b =>
                {
                    b.Property<int>("DepartmentsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StaffID")
                        .HasColumnType("int");

                    b.HasKey("DepartmentsID");

                    b.HasIndex("StaffID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("AvcolStaff.Models.PersonalInformation", b =>
                {
                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BirthPlace")
                        .IsRequired()
                        .HasColumnType("nvarchar(56)")
                        .HasMaxLength(56);

                    b.Property<string>("CitizenStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EcRelaitonship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IrdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffID");

                    b.ToTable("PersonalInformation");
                });

            modelBuilder.Entity("AvcolStaff.Models.Rating", b =>
                {
                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.Property<int>("ReviewStars")
                        .HasColumnType("int");

                    b.HasKey("StaffID");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("AvcolStaff.Models.Roles", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StaffID1")
                        .HasColumnType("int");

                    b.HasKey("StaffID");

                    b.HasIndex("StaffID1");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("AvcolStaff.Models.Salary", b =>
                {
                    b.Property<int>("SalaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("ActualSalary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EndRange")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MoeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalaryGradeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.Property<decimal>("StartRange")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SalaryID");

                    b.ToTable("Salary");
                });

            modelBuilder.Entity("AvcolStaff.Models.Sessions", b =>
                {
                    b.Property<int>("StaffID")
                        .HasColumnType("int");

                    b.Property<string>("Day")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubjectsID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("StaffID");

                    b.HasIndex("SubjectsID")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("AvcolStaff.Models.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(35)")
                        .HasMaxLength(35);

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(35)")
                        .HasMaxLength(35);

                    b.Property<string>("TeacherCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)")
                        .HasMaxLength(3);

                    b.HasKey("StaffID");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("AvcolStaff.Models.Standards", b =>
                {
                    b.Property<int>("SubjectsID")
                        .HasColumnType("int");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("StaffID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardName")
                        .HasColumnType("nvarchar(60)")
                        .HasMaxLength(60);

                    b.HasKey("SubjectsID");

                    b.ToTable("Standards");
                });

            modelBuilder.Entity("AvcolStaff.Models.Subjects", b =>
                {
                    b.Property<int>("SubjectsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentsID")
                        .HasColumnType("int");

                    b.Property<string>("SubjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCredits")
                        .HasColumnType("int");

                    b.HasKey("SubjectsID");

                    b.HasIndex("DepartmentsID");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("AvcolStaff.Models.Departments", b =>
                {
                    b.HasOne("AvcolStaff.Models.Staff", "Staff")
                        .WithMany("Departments")
                        .HasForeignKey("StaffID");
                });

            modelBuilder.Entity("AvcolStaff.Models.PersonalInformation", b =>
                {
                    b.HasOne("AvcolStaff.Models.Staff", "Staff")
                        .WithOne("PersonalInformation")
                        .HasForeignKey("AvcolStaff.Models.PersonalInformation", "StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AvcolStaff.Models.Rating", b =>
                {
                    b.HasOne("AvcolStaff.Models.Staff", "Staff")
                        .WithOne("Rating")
                        .HasForeignKey("AvcolStaff.Models.Rating", "StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AvcolStaff.Models.Roles", b =>
                {
                    b.HasOne("AvcolStaff.Models.Staff", "Staff")
                        .WithMany()
                        .HasForeignKey("StaffID1");
                });

            modelBuilder.Entity("AvcolStaff.Models.Sessions", b =>
                {
                    b.HasOne("AvcolStaff.Models.Staff", "Staff")
                        .WithOne("Sessions")
                        .HasForeignKey("AvcolStaff.Models.Sessions", "StaffID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AvcolStaff.Models.Subjects", "subjects")
                        .WithOne("Sessions")
                        .HasForeignKey("AvcolStaff.Models.Sessions", "SubjectsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AvcolStaff.Models.Standards", b =>
                {
                    b.HasOne("AvcolStaff.Models.Subjects", "Subjects")
                        .WithOne("Standards")
                        .HasForeignKey("AvcolStaff.Models.Standards", "SubjectsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AvcolStaff.Models.Subjects", b =>
                {
                    b.HasOne("AvcolStaff.Models.Departments", "Departments")
                        .WithMany()
                        .HasForeignKey("DepartmentsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
